#!/bin/bash
# Run a .cc file quickly, like `go run xyz.go` would compile and run `xyz.go`,
# `cpprun xyz.cc` would compile and run `xyz.cc`.
#
# Synposis:
#   cpprun xyz.cc [arguments to xyz.cc]

set -o errexit

EXT_REGEX_OPT="-r"
if [[ "$(uname)" == "Darwin" ]]; then
  EXT_REGEX_OPT="-E"
fi

CPPFILE="$1"
shift
EXEFILE="$(echo "${CPPFILE}" | sed "${EXT_REGEX_OPT}" 's/(.*)\.cc$/\1/')"
clang++ -std=c++0x  -g -o "${EXEFILE}" "${CPPFILE}"
"${EXEFILE}" "$@"
