#!/bin/bash
# Run a .cpp file quickly, like `go run xyz.go` would compile and run `xyz.go`,
# `cpprun xyz.cpp` would compile and run `xyz.c`.
#
# Synposis:
#   cpprun xyz.cpp [arguments to xyz.cpp]

CPPFILE="$1"
shift
EXEFILE="$(echo "${CPPFILE}" | sed -r 's/(.*)\.cpp$/\1/')"
g++ -std=c++0x  -g -o "${EXEFILE}" "${CPPFILE}"
"./${EXEFILE}" "$@"
