#!/bin/bash
# Run a .c file quickly, like `go run xyz.go` would compile and run `xyz.go`,
# `crun xyz.c` would compile and run `xyz.c`.
#
# Synposis:
#   crun xyz.c [arguments to xyz.c]

set -o errexit

EXT_REGEX_OPT="-r"
if [[ "$(uname)" == "Darwin" ]]; then
  EXT_REGEX_OPT="-E"
fi

CFILE="$1"
shift
EXEFILE="$(echo "${CFILE}" | sed "${EXT_REGEX_OPT}" 's/(.*)\.c/\1/')"
clang -g -o "${EXEFILE}" "${CFILE}"
"${EXEFILE}" "$@"
